# Generated by Django 4.1.3 on 2022-11-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_competition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
