# Generated by Django 4.1.3 on 2022-11-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_delete_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('participant_name', models.CharField(max_length=50)),
                ('identification', models.BigIntegerField()),
                ('city', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('category_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.categorycompetition')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
